// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoeWqXkaaRkmLKcd-vrid7l4hsYlgldow',
    appId: '1:160438197952:web:934cd123aa8f3910f75725',
    messagingSenderId: '160438197952',
    projectId: 'smartlib-e123d',
    authDomain: 'smartlib-e123d.firebaseapp.com',
    storageBucket: 'smartlib-e123d.firebasestorage.app',
    measurementId: 'G-CDW7M7Q80L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhgRAlGb0Bysd847IEbgJw3Ir6cKwSRL8',
    appId: '1:160438197952:android:9c0ea8d58e887564f75725',
    messagingSenderId: '160438197952',
    projectId: 'smartlib-e123d',
    storageBucket: 'smartlib-e123d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv5DnhPb7lws7DCmO6tSRYWigWjoGKLcQ',
    appId: '1:160438197952:ios:3fa8cbc2054a1542f75725',
    messagingSenderId: '160438197952',
    projectId: 'smartlib-e123d',
    storageBucket: 'smartlib-e123d.firebasestorage.app',
    iosBundleId: 'com.example.smartlib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv5DnhPb7lws7DCmO6tSRYWigWjoGKLcQ',
    appId: '1:160438197952:ios:3fa8cbc2054a1542f75725',
    messagingSenderId: '160438197952',
    projectId: 'smartlib-e123d',
    storageBucket: 'smartlib-e123d.firebasestorage.app',
    iosBundleId: 'com.example.smartlib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoeWqXkaaRkmLKcd-vrid7l4hsYlgldow',
    appId: '1:160438197952:web:310a528d1223ecbdf75725',
    messagingSenderId: '160438197952',
    projectId: 'smartlib-e123d',
    authDomain: 'smartlib-e123d.firebaseapp.com',
    storageBucket: 'smartlib-e123d.firebasestorage.app',
    measurementId: 'G-FT1QE93E0Y',
  );
}
